# Generated by Django 4.1.1 on 2022-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_client_email_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
